# Generated by Django 4.1.6 on 2023-02-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefix', models.CharField(max_length=255, null=True)),
                ('First', models.CharField(max_length=255)),
                ('Last', models.CharField(max_length=255)),
                ('Suffix', models.CharField(max_length=255, null=True)),
                ('FilingType', models.CharField(max_length=1)),
                ('StateDst', models.CharField(max_length=255)),
                ('Year', models.IntegerField()),
                ('FilingDate', models.DateField()),
                ('DocID', models.IntegerField(unique=True)),
            ],
        ),
    ]
