# Generated by Django 4.1.6 on 2023-02-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tradetracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(max_length=255)),
                ('Transaction', models.CharField(max_length=2)),
                ('Quantity', models.IntegerField()),
                ('StrikePrice', models.IntegerField(null=True)),
                ('ExpirationData', models.DateField(null=True)),
                ('DocID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradetracking.filing')),
            ],
        ),
    ]
