name: redeploy

on:
  push:
    branches: [ 'master' ]

env:
  SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  REMOTE_HOST: dev-api.nancybot.noahkmoore.com

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Setup SSH Key
        uses: appleboy/ssh-action@master
        with:
          ssh-private-key: ${{ env.SSH_KEY }}

      - name: Run Docker Compose on Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.REMOTE_HOST }}
          username: atlascapital
          script: |
            cd /home/atlascapital/nancybot
            touch .env.dev
            echo "${{ secrets.SERVER_ENV_DEV }}" > .env.dev
            cat .env.dev
            git pull
            docker-compose build --pull && docker-compose up --build --remove-orphans -d